name: Main CI 
on:
  push:
    branches: -master
jobs:
  build:
    runs-on: ubuntu-18.04 
    steps:
      - name: 개시발
        uses: actions/checkout@v2

      - name: npm install
        run: npm install 

      - name: build
        run: npm run build

      # - name: deploy
      #   env: 
      #     AWS_ACCESS_KEY_ID: '${{ secrets.ACCESS_KEY_ID }}'
      #     AWS_SECRET_ACCESS_KEY: '${{ secrets.ACCESS_KEY_SECRET }}'
        # run: | 
        #   aws s3 cp \ 
        #     --recursive \
        #     --region ap-northeast-2 \
        #     dist s3://vue-github-action-Noolim